In [2]:
import numpy as np

In [12]:
import random

In [33]:
from numpy import linalg

In [76]:
import matplotlib.pyplot as plt

**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
np.arange(0, 25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [32]:
z = np.arange(25).reshape(5,5)
print(z)
print(z.trace())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
60


**Задание 3**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [63]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [64]:
b = np.array( [4, 12, -3] )

In [72]:
d = linalg.solve(a, b)
v = list(d)
print('Ответ: x = ', v[0], 'y = ', v[1], 'z = ', v[2])

Ответ: x =  0.4666666666666668 y =  3.844444444444444 z =  -5.555555555555555


In [73]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

**Задание 4**
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [86]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [75]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [145]:
def arcos ():
    i = []
    for users_stats_new in users_stats:
        aLength = np.linalg.norm( users_stats_new )
        bLength = np.linalg.norm( next_user_stats )
        x = np.dot(users_stats_new, next_user_stats) / ( aLength * bLength )
        y = np.arccos( x ) * 360 / 2 / np.pi
        i.append(y)
    return i
arcos()


[78.46304096718453,
 32.311533237423866,
 66.42182152179818,
 37.761243907035045,
 66.42182152179818,
 90.0,
 90.0,
 18.434948822922017,
 90.0,
 90.0]

In [146]:
arcos() 

[78.46304096718453,
 32.311533237423866,
 66.42182152179818,
 37.761243907035045,
 66.42182152179818,
 90.0,
 90.0,
 18.434948822922017,
 90.0,
 90.0]

In [148]:
for ID in range(len(i)):
    if pattern == i[ID]:
        print('ID самого похожего польхователя: ', ID+1)

ID самого похожего польхователя:  8
